name: Build Documentation

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Env
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        init-shell: bash
      run: pip install -vv .
      
    - name: Install docs dependencies
      run: |
        pip install -r docs/requirements.txt

    - name: Build Sphinx Documentation
      run: |
        cd docs
        make html
      shell: bash -el {0}
